ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS "mediaUrl" TEXT;
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS "mediaType" TEXT;
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS "mediaSize" INTEGER;
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS "mediaName" TEXT;
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS "isEdited" BOOLEAN DEFAULT false;
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS "editedAt" TIMESTAMP(3);
